[package]
name = "markov"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.93"
rand = { version = "0.8.5", features = ["small_rng"] }
tev_client = "0.5.2"
numpy = "0.22.1"
pyo3 = { version = "0.22", features = ["extension-module"] }
memchr = "2.7.4"
rayon = "1.10.0"
