[package]
name = "markov"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow = "1.0.93"
rand = { version = "0.8.5", features = ["small_rng"] }
tev_client = "0.5.2"
numpy = "0.23.0"
pyo3 = { version = "0.23", features = ["extension-module"] }
memchr = "2.7.4"
rayon = "1.10.0"
block-mesh = "0.2.0"
bytemuck = { version = "1.20.0", features = ["derive"] }
ndshape = "0.3.0"
arrayvec = "0.7.6"
indexmap = "2.7.0"
ordered-float = "4.5.0"
num-traits = "0.2.19"
fnv = "1.0.7"

[build-dependencies]
xml = "0.8.20"

[profile.release-with-debug]
inherits = "release"
debug = true

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "my_benchmark"
harness = false
