[package]
name = "markov"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.75"
glam = "0.25.0"
rand = { version = "0.8.5", features = ["small_rng"] }
tev_client = "0.5.2"
numpy = "0.20.0"
pyo3 = { version = "0.20.0", features = ["extension-module"] }
#regex = "1.10.2"
memchr = "2.6.4"
rayon = "1.8.0"
